"""Coaching emails: the Monday report and the four-hour pre-meeting brief.

  send_weekly_report(db)  Mondays 9:00 AM America/Chicago. Every client, every
                          open commitment, every objective, and where each
                          engagement is heading — one email, whole book.

  send_meeting_prep(db)   Swept every 10 minutes. Four hours before a coaching
                          session starts, the coach gets that call's agenda:
                          last week's commitments with a verdict on each, the
                          discussion checklist, and what is overdue.

Both are idempotent. The prep mail stamps `prep_sent_at` on the meeting; the
weekly report stamps a per-week key in `coaching_email_log`. A scheduler misfire
that replays a job therefore costs nothing.
"""
import asyncio
import logging
import os
from datetime import datetime, timedelta

from services.brevo import app_url, send_email
from services.coaching_core import (
    OWNER_CLIENT,
    fmt_day,
    fmt_when,
    iso,
    local,
    now_utc,
    parse_dt,
    status_label,
    week_start,
)
from services.coaching_store import (
    get_client,
    list_clients,
    log_email,
    mark_prep_sent,
    master_rows,
    meetings_starting_between,
    snapshot_or_refresh,
)

logger = logging.getLogger(__name__)

# How far ahead of a session the prep email goes out.
PREP_LEAD_HOURS = int(os.environ.get("COACHING_PREP_LEAD_HOURS", "4"))

INK = "#1F140A"
CREAM = "#F4F0E8"
GOLD = "#B68A35"
MUTED = "#6B5B44"
RULE = "#E0D5C0"
RED = "#9B2226"
GREEN = "#2F6B4F"

_VERDICT_STYLE = {
    "kept": (GREEN, "Kept"),
    "working": (GOLD, "In process"),
    "pending": (MUTED, "Pending"),
    "missed": (RED, "Missed"),
    "dropped": (MUTED, "Dropped"),
}

_DIRECTION_COLOR = {
    "accelerating": GREEN,
    "steady": GOLD,
    "drifting": "#B4631C",
    "stalled": RED,
}


# ------------------------------------------------------------------ markup

def esc(text) -> str:
    return (
        str(text or "")
        .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _wrap(title: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)}</title></head>
<body style="margin:0;padding:0;background:{CREAM};">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:{CREAM};padding:24px 12px;">
<tr><td align="center">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#FFFDF8;border:1px solid {RULE};">
<tr><td style="padding:24px 28px 8px 28px;font-family:Georgia,serif;">
  <div style="font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:{GOLD};">Coaching</div>
  <h1 style="margin:6px 0 0 0;font-size:22px;line-height:1.25;color:{INK};font-weight:normal;">{esc(title)}</h1>
</td></tr>
<tr><td style="padding:8px 28px 28px 28px;font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;font-size:14px;line-height:1.55;color:{INK};">
{body}
</td></tr>
</table>
<div style="max-width:640px;margin:12px auto 0;font-family:-apple-system,Segoe UI,Helvetica,Arial,sans-serif;font-size:11px;color:{MUTED};text-align:center;">
  Generated by your coaching dashboard.
</div>
</td></tr></table></body></html>"""


def _h2(text: str) -> str:
    return (
        f'<div style="margin:22px 0 8px 0;padding-bottom:5px;border-bottom:1px solid {RULE};'
        f'font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:{MUTED};">{esc(text)}</div>'
    )


def _pill(text: str, color: str) -> str:
    return (
        f'<span style="display:inline-block;padding:1px 7px;border:1px solid {color};'
        f'border-radius:2px;font-size:10px;letter-spacing:.06em;text-transform:uppercase;'
        f'color:{color};">{esc(text)}</span>'
    )


def _button(label: str, href: str) -> str:
    return (
        f'<a href="{esc(href)}" style="display:inline-block;padding:9px 18px;background:{GOLD};'
        f'color:#FFFDF8;text-decoration:none;font-size:13px;letter-spacing:.03em;">{esc(label)}</a>'
    )


def _trajectory_line(traj: dict) -> str:
    color = _DIRECTION_COLOR.get(traj.get("direction"), GOLD)
    return (
        f'<div style="margin:2px 0 10px 0;">{_pill(traj.get("direction_label", "—"), color)}'
        f'<span style="color:{MUTED};font-size:12px;margin-left:8px;">'
        f'{traj.get("score", 0)}/100 · {traj.get("completion_rate", 0)}% of commitments closed</span></div>'
    )


def _commitment_rows(review: list[dict], limit: int = 12) -> str:
    if not review:
        return f'<div style="color:{MUTED};font-style:italic;">No commitments were on the board this week.</div>'
    out = []
    for c in review[:limit]:
        color, label = _VERDICT_STYLE.get(c.get("verdict"), (MUTED, "—"))
        extra = ""
        if c.get("verdict") == "missed" and c.get("days_overdue"):
            extra = f' · {c["days_overdue"]}d past due'
        elif c.get("due_label"):
            extra = f' · due {esc(c["due_label"])}'
        who = "" if c.get("owner") == OWNER_CLIENT else f' · <em style="color:{MUTED};">yours</em>'
        out.append(
            f'<tr><td style="padding:6px 10px 6px 0;vertical-align:top;white-space:nowrap;">{_pill(label, color)}</td>'
            f'<td style="padding:6px 0;vertical-align:top;">{esc(c.get("title"))}'
            f'<span style="color:{MUTED};font-size:12px;">{extra}{who}</span></td></tr>'
        )
    return f'<table role="presentation" cellpadding="0" cellspacing="0" width="100%">{"".join(out)}</table>'


def _checklist_html(items: list[dict], limit: int = 12) -> str:
    if not items:
        return f'<div style="color:{MUTED};font-style:italic;">Nothing flagged — run your standard agenda.</div>'
    out = []
    for i, item in enumerate(items[:limit], 1):
        detail = (
            f'<div style="color:{MUTED};font-size:12px;margin-top:1px;">{esc(item.get("detail"))}</div>'
            if item.get("detail") else ""
        )
        out.append(
            f'<tr><td style="padding:7px 10px 7px 0;vertical-align:top;color:{GOLD};'
            f'font-family:Georgia,serif;">{i}.</td>'
            f'<td style="padding:7px 0;vertical-align:top;">{esc(item.get("label"))}{detail}</td></tr>'
        )
    return f'<table role="presentation" cellpadding="0" cellspacing="0" width="100%">{"".join(out)}</table>'


def _action_list(actions: list[dict], limit: int = 10) -> str:
    if not actions:
        return f'<div style="color:{MUTED};font-style:italic;">None.</div>'
    out = []
    for a in actions[:limit]:
        due = f' <span style="color:{MUTED};font-size:12px;">· due {esc(fmt_day(a.get("due_date")))}</span>' if a.get("due_date") else ""
        out.append(
            f'<div style="padding:4px 0;">'
            f'<span style="color:{MUTED};font-size:11px;text-transform:uppercase;letter-spacing:.06em;">'
            f'{esc(status_label(a.get("status")))}</span>&nbsp; {esc(a.get("title"))}{due}</div>'
        )
    return "".join(out)


# ------------------------------------------------------- pre-meeting brief

def build_prep_email_html(client: dict, meeting: dict, agenda: dict, portal_url: str = "") -> str:
    traj = agenda.get("trajectory") or {}
    counts = agenda.get("counts") or {}
    name = client.get("name") or "your client"
    body = [
        f'<div style="font-size:15px;color:{INK};margin-bottom:2px;">'
        f'<strong>{esc(meeting.get("title") or f"Coaching — {name}")}</strong></div>',
        f'<div style="color:{MUTED};font-size:13px;">{esc(fmt_when(meeting.get("starts_at")))}'
        + (f' · {esc(meeting.get("location"))}' if meeting.get("location") else "")
        + "</div>",
        _trajectory_line(traj),
    ]

    if agenda.get("running_summary"):
        body.append(_h2("Where things stand"))
        body.append(f'<div>{esc(agenda["running_summary"])}</div>')

    read = (agenda.get("trajectory_read") or {})
    if read.get("coach_move"):
        body.append(
            f'<div style="margin-top:12px;padding:10px 12px;background:{CREAM};border-left:2px solid {GOLD};">'
            f'<span style="font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:{MUTED};">'
            f'Highest-leverage move</span><br>{esc(read["coach_move"])}</div>'
        )

    body.append(_h2("Last week's commitments"))
    body.append(_commitment_rows(agenda.get("commitments_review") or []))

    body.append(_h2("Discuss on this call"))
    body.append(_checklist_html(agenda.get("checklist") or []))

    overdue = agenda.get("overdue") or []
    if overdue:
        body.append(_h2(f"Overdue ({len(overdue)})"))
        body.append(_action_list(overdue))

    body.append(_h2("Open items"))
    body.append(_action_list(agenda.get("open_items") or []))
    body.append(
        f'<div style="margin-top:6px;color:{MUTED};font-size:12px;">'
        f'{counts.get("completed", 0)} completed · {counts.get("in_process", 0)} in process · '
        f'{counts.get("incomplete", 0)} incomplete</div>'
    )

    if portal_url:
        body.append(f'<div style="margin-top:24px;">{_button("Open the dashboard", portal_url)}</div>')

    return _wrap(f"In {PREP_LEAD_HOURS} hours: {name}", "".join(body))


async def _coach_contact(db, client: dict) -> tuple[str, str] | None:
    """Who gets the coach-side mail for this client."""
    coach_id = client.get("coach_user_id")
    if coach_id:
        user = await db.users.find_one({"user_id": coach_id}, {"_id": 0, "email": 1, "name": 1})
        if user and user.get("email"):
            return user["email"], user.get("name") or ""
    fallback = os.environ.get("COACHING_COACH_EMAIL", "")
    return (fallback, os.environ.get("COACHING_COACH_NAME", "")) if fallback else None


async def send_meeting_prep(db) -> dict:
    """Send the pre-meeting brief for every session starting inside the lead
    window that hasn't had one yet.

    Window rather than an exact instant so a meeting booked three hours before
    it starts still gets a brief, and so a missed scheduler tick doesn't skip
    anyone. `prep_sent_at` is what actually prevents a second send.
    """
    now = now_utc()
    horizon = now + timedelta(hours=PREP_LEAD_HOURS)
    meetings = await meetings_starting_between(db, now, horizon)
    sent, skipped, failed = 0, 0, 0

    for meeting in meetings:
        if meeting.get("prep_sent_at"):
            skipped += 1
            continue
        try:
            client = await get_client(db, meeting["client_id"])
            if not client or client.get("status") == "archived":
                skipped += 1
                continue
            contact = await _coach_contact(db, client)
            if not contact:
                logger.warning("coaching: no coach email for client %s; skipping prep mail", client["client_id"])
                skipped += 1
                continue

            snap = await snapshot_or_refresh(db, client["client_id"])
            agenda = dict((snap or {}).get("agenda") or {})
            agenda["meeting"] = {
                "meeting_id": meeting.get("meeting_id"),
                "title": meeting.get("title"),
                "starts_at": meeting.get("starts_at"),
                "when_label": fmt_when(meeting.get("starts_at")),
                "location": meeting.get("location") or "",
            }

            portal_url = f"{app_url()}/coaching/client/{client['client_id']}"
            html = build_prep_email_html(client, meeting, agenda, portal_url)
            review = agenda.get("commitments_review") or []
            owed = sum(1 for c in review if c.get("verdict") in ("missed", "working", "pending"))
            subject = (
                f"In {PREP_LEAD_HOURS}h: {client.get('name')} — "
                f"{owed} commitment{'s' if owed != 1 else ''} to review"
                if owed else f"In {PREP_LEAD_HOURS}h: {client.get('name')}"
            )

            result = await asyncio.to_thread(
                send_email, contact[0], contact[1], subject, html, ["coaching", "coaching_prep"],
            )
            await mark_prep_sent(db, meeting["meeting_id"], now)
            await log_email(
                db, kind="coaching_prep", to_email=contact[0],
                client_id=client["client_id"], meeting_id=meeting["meeting_id"], result=result,
            )
            sent += 1
        except Exception:
            failed += 1
            logger.exception("coaching: prep email failed for meeting %s", meeting.get("meeting_id"))

    if sent or failed:
        logger.info("coaching prep sweep: %s sent, %s skipped, %s failed", sent, skipped, failed)
    return {"sent": sent, "skipped": skipped, "failed": failed, "considered": len(meetings)}


# ----------------------------------------------------------- weekly report

def build_weekly_report_html(rows: list[dict], now: datetime, base_url: str = "") -> str:
    week_label = local(now).strftime("Week of %B %-d, %Y")
    total_open = sum(r["counts"]["open_total"] for r in rows)
    total_overdue = sum(r["counts"]["overdue"] for r in rows)
    total_done = sum(len(r.get("wins") or []) for r in rows)

    body = [
        f'<div style="color:{MUTED};font-size:13px;">{esc(week_label)} · {len(rows)} active client'
        f'{"s" if len(rows) != 1 else ""}</div>',
        f'<div style="margin:14px 0 4px 0;padding:12px 14px;background:{CREAM};">'
        f'<span style="font-size:20px;font-family:Georgia,serif;">{total_done}</span>'
        f'<span style="color:{MUTED};font-size:12px;"> closed last week</span>'
        f'&nbsp;&nbsp;·&nbsp;&nbsp;<span style="font-size:20px;font-family:Georgia,serif;">{total_open}</span>'
        f'<span style="color:{MUTED};font-size:12px;"> open</span>'
        f'&nbsp;&nbsp;·&nbsp;&nbsp;<span style="font-size:20px;font-family:Georgia,serif;color:{RED if total_overdue else INK};">{total_overdue}</span>'
        f'<span style="color:{MUTED};font-size:12px;"> overdue</span></div>',
    ]

    upcoming = [r for r in rows if r.get("next_meeting")]
    if upcoming:
        body.append(_h2("On the calendar this week"))
        lines = []
        for r in sorted(upcoming, key=lambda r: r["next_meeting"]["starts_at"]):
            starts = parse_dt(r["next_meeting"]["starts_at"])
            if not starts or starts > now + timedelta(days=8):
                continue
            lines.append(
                f'<div style="padding:3px 0;"><strong>{esc(r["name"])}</strong>'
                f'<span style="color:{MUTED};"> — {esc(fmt_when(r["next_meeting"]["starts_at"]))}</span></div>'
            )
        body.append("".join(lines) or f'<div style="color:{MUTED};font-style:italic;">Nothing booked.</div>')

    for r in rows:
        traj = r["trajectory"]
        counts = r["counts"]
        color = _DIRECTION_COLOR.get(traj.get("direction"), GOLD)
        header = (
            f'<div style="margin:26px 0 0 0;padding-top:14px;border-top:2px solid {RULE};">'
            f'<span style="font-family:Georgia,serif;font-size:17px;">{esc(r["name"])}</span>'
            f'&nbsp;&nbsp;{_pill(traj.get("direction_label", "—"), color)}'
            f'<div style="color:{MUTED};font-size:12px;margin-top:3px;">'
            f'{traj.get("score", 0)}/100 · {counts["completed"]} completed · {counts["in_process"]} in process · '
            f'{counts["incomplete"]} incomplete'
            + (f' · <span style="color:{RED};">{counts["overdue"]} overdue</span>' if counts["overdue"] else "")
            + (f' · next: {esc(fmt_when(r["next_meeting"]["starts_at"]))}' if r.get("next_meeting") else " · nothing booked")
            + "</div></div>"
        )
        body.append(header)

        if r.get("running_summary"):
            body.append(f'<div style="margin-top:8px;font-size:13px;">{esc(r["running_summary"])}</div>')

        body.append(
            f'<div style="margin-top:10px;font-size:11px;letter-spacing:.12em;'
            f'text-transform:uppercase;color:{MUTED};">Past week</div>'
        )
        body.append(_commitment_rows(r.get("commitments_review") or [], limit=8))

        if r.get("checklist"):
            body.append(
                f'<div style="margin-top:12px;font-size:11px;letter-spacing:.12em;'
                f'text-transform:uppercase;color:{MUTED};">Bring to the next call</div>'
            )
            body.append(_checklist_html(r["checklist"], limit=6))

        for risk in (traj.get("risks") or [])[:2]:
            body.append(
                f'<div style="margin-top:8px;color:{RED};font-size:12px;">▲ {esc(risk)}</div>'
            )

    if base_url:
        body.append(f'<div style="margin-top:28px;">{_button("Open the master dashboard", f"{base_url}/coaching")}</div>')

    return _wrap("Your coaching week", "".join(body))


async def send_weekly_report(db) -> dict:
    """Monday 9:00 AM America/Chicago — the whole book in one email.

    Grouped by coach so a multi-coach practice works, with the
    COACHING_COACH_EMAIL fallback covering the single-coach setup where
    clients carry no coach_user_id.
    """
    now = now_utc()
    week_key = week_start(now).date().isoformat()

    already = await db.coaching_email_log.find_one({"kind": "coaching_weekly", "week_key": week_key})
    if already:
        logger.info("coaching weekly report already sent for week %s", week_key)
        return {"skipped": True, "week": week_key}

    clients = await list_clients(db)
    if not clients:
        return {"sent": 0, "reason": "no active clients"}

    # Group clients by the coach who should receive their rollup.
    by_coach: dict[tuple[str, str], list[str]] = {}
    for client in clients:
        contact = await _coach_contact(db, client)
        if not contact:
            continue
        by_coach.setdefault(contact, []).append(client["client_id"])

    if not by_coach:
        logger.warning("coaching weekly: no coach recipients resolved; set COACHING_COACH_EMAIL")
        return {"sent": 0, "reason": "no recipients"}

    sent = 0
    all_rows = await master_rows(db)
    for (email, name), client_ids in by_coach.items():
        rows = [r for r in all_rows if r["client_id"] in client_ids]
        if not rows:
            continue
        html = build_weekly_report_html(rows, now, app_url())
        overdue = sum(r["counts"]["overdue"] for r in rows)
        subject = (
            f"Coaching week — {len(rows)} client{'s' if len(rows) != 1 else ''}"
            + (f", {overdue} overdue" if overdue else "")
        )
        result = await asyncio.to_thread(
            send_email, email, name, subject, html, ["coaching", "coaching_weekly"],
        )
        await log_email(db, kind="coaching_weekly", to_email=email, result=result)
        sent += 1

    await db.coaching_email_log.update_one(
        {"kind": "coaching_weekly", "week_key": week_key},
        {"$set": {"kind": "coaching_weekly", "week_key": week_key, "sent": sent, "created_at": iso(now)}},
        upsert=True,
    )
    logger.info("coaching weekly report sent to %s coach(es) for week %s", sent, week_key)
    return {"sent": sent, "week": week_key, "clients": len(clients)}


# ------------------------------------------------------- portal invitation

def build_portal_invite_html(client: dict, portal_url: str, coach_name: str = "") -> str:
    from_line = f" from {esc(coach_name)}" if coach_name else ""
    body = [
        f'<div>Hi {esc((client.get("name") or "").split(" ")[0])},</div>',
        f'<div style="margin-top:12px;">Here is your private coaching dashboard{from_line}. '
        f'It keeps a running summary of our conversations, everything you have committed to, '
        f'and where each item stands — completed, in process, or still open.</div>',
        '<div style="margin-top:12px;">You can mark items done as you go; I see the updates '
        'before our next call.</div>',
        f'<div style="margin:22px 0;">{_button("Open my dashboard", portal_url)}</div>',
        f'<div style="color:{MUTED};font-size:12px;">This link is private to you — treat it '
        f'like a password. Tell me if you ever need it reissued.</div>',
    ]
    return _wrap("Your coaching dashboard", "".join(body))
