"""Tests for iteration_8 media features: image gallery, video, audio, URL embed.
Covers /api/uploads, /api/uploads/embed, posts/essays/drafts media[] persistence."""
import os
import io
import subprocess
import time
import pytest
import requests

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "https://agg-reader-first.preview.emergentagent.com").rstrip("/")

# These fixture files are generated by conftest below
SHORT_MP4 = "/tmp/short.mp4"
LONG_MP4 = "/tmp/long.mp4"
AUDIO_MP3 = "/tmp/audio.mp3"
LONG_AUDIO_MP3 = "/tmp/longaudio.mp3"
BIG_FAKE_VIDEO = "/tmp/big.mp4"


def _ensure_fixtures():
    if not os.path.exists(SHORT_MP4):
        subprocess.run(["ffmpeg", "-y", "-f", "lavfi", "-i", "testsrc=duration=3:size=320x240:rate=15",
                        "-c:v", "libx264", "-pix_fmt", "yuv420p", SHORT_MP4, "-loglevel", "error"], check=True)
    if not os.path.exists(LONG_MP4):
        subprocess.run(["ffmpeg", "-y", "-f", "lavfi", "-i", "testsrc=duration=65:size=320x240:rate=15",
                        "-c:v", "libx264", "-pix_fmt", "yuv420p", LONG_MP4, "-loglevel", "error"], check=True)
    if not os.path.exists(AUDIO_MP3):
        subprocess.run(["ffmpeg", "-y", "-f", "lavfi", "-i", "sine=frequency=440:duration=2",
                        "-c:a", "libmp3lame", AUDIO_MP3, "-loglevel", "error"], check=True)
    if not os.path.exists(LONG_AUDIO_MP3):
        subprocess.run(["ffmpeg", "-y", "-f", "lavfi", "-i", "sine=frequency=440:duration=310",
                        "-c:a", "libmp3lame", LONG_AUDIO_MP3, "-loglevel", "error"], check=True)


def _seed_user(is_admin=False):
    """Insert an approved test user + session via mongosh; return token."""
    suffix = str(int(time.time() * 1000))
    uid = f"user_mt_{suffix}"
    tok = f"tok_mt_{suffix}"
    email = f"peter@1691inc.com" if is_admin else f"mt.{suffix}@example.com"
    script = f"""
use('test_database');
db.users.insertOne({{
  user_id: '{uid}', email: '{email}', name: 'MT', picture: '',
  is_admin: {str(is_admin).lower()}, status: 'approved', source: 'manual_test',
  created_at: new Date().toISOString(), last_login_at: new Date().toISOString()
}});
db.user_sessions.insertOne({{
  user_id: '{uid}', session_token: '{tok}',
  created_at: new Date().toISOString(),
  expires_at: new Date(Date.now() + 7*24*60*60*1000).toISOString()
}});
"""
    subprocess.run(["mongosh", "--quiet", "--eval", script], check=True, capture_output=True)
    return tok, uid


@pytest.fixture(scope="session", autouse=True)
def fixtures():
    _ensure_fixtures()
    yield


@pytest.fixture(scope="session")
def member_token():
    tok, _ = _seed_user(is_admin=False)
    return tok


@pytest.fixture(scope="session")
def member_headers(member_token):
    return {"Authorization": f"Bearer {member_token}"}


# ---------- /api/uploads images ----------

class TestImageUpload:
    def test_upload_image_jpg(self, member_headers):
        # Tiny 1x1 JPEG bytes
        jpg = bytes.fromhex(
            "ffd8ffe000104a46494600010100000100010000ffdb004300080606070605"
            "0807070709090808090b0e0c0b0a0a0b160e0f0c1014131717141312131815"
            "1a221c19181e1e1e1f1c191e1c1e1f23292924221e221f3933272c2e313131"
            "ffc00011080001000103012200021101031101ffc4001f00000105010101"
            "01010100000000000000000102030405060708090a0bffc400b510000201"
            "030302040305050404000001"  # truncated but enough for upload (server validates by mime)
        )
        # Actually create a valid JPEG via ffmpeg lavfi color frame
        import tempfile
        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as t:
            tmp = t.name
        subprocess.run(["ffmpeg", "-y", "-f", "lavfi", "-i", "color=c=red:s=10x10:d=1",
                        "-frames:v", "1", tmp, "-loglevel", "error"], check=True)
        with open(tmp, "rb") as f:
            data = f.read()
        os.unlink(tmp)
        files = {"file": ("test.jpg", data, "image/jpeg")}
        r = requests.post(f"{BASE_URL}/api/uploads", headers=member_headers, files=files, data={"kind": "posts"})
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["media_kind"] == "image"
        assert body["path"]

    def test_upload_image_oversized(self, member_headers):
        big = b"\xff\xd8\xff\xe0" + b"\x00" * (7 * 1024 * 1024)
        files = {"file": ("big.jpg", big, "image/jpeg")}
        r = requests.post(f"{BASE_URL}/api/uploads", headers=member_headers, files=files)
        assert r.status_code == 413


# ---------- /api/uploads video ----------

class TestVideoUpload:
    def test_upload_short_video(self, member_headers):
        with open(SHORT_MP4, "rb") as f:
            data = f.read()
        files = {"file": ("short.mp4", data, "video/mp4")}
        r = requests.post(f"{BASE_URL}/api/uploads", headers=member_headers, files=files)
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["media_kind"] == "video"
        assert body["duration_s"] > 0
        assert body["width"] > 0 and body["height"] > 0
        assert "thumbnail_path" in body and body["thumbnail_path"]
        # Verify thumbnail retrievable
        tr = requests.get(f"{BASE_URL}/api/uploads/file/{body['thumbnail_path']}")
        assert tr.status_code == 200
        # JPEG magic bytes
        assert tr.content[:3] == b"\xff\xd8\xff"

    def test_upload_long_video_now_queues_hls(self, member_headers):
        # Phase 7: 65s video is no longer rejected; it returns processing=True + transcode_job_id.
        with open(LONG_MP4, "rb") as f:
            data = f.read()
        files = {"file": ("long.mp4", data, "video/mp4")}
        r = requests.post(f"{BASE_URL}/api/uploads", headers=member_headers, files=files)
        assert r.status_code == 200, r.text
        body = r.json()
        assert body.get("processing") is True
        assert body.get("transcode_job_id")
        assert "path" not in body

    def test_upload_oversized_video(self, member_headers):
        # Phase 7: HLS cap is 200MB; 210MB should still 413
        big = b"\x00" * (210 * 1024 * 1024)
        files = {"file": ("big.mp4", big, "video/mp4")}
        r = requests.post(f"{BASE_URL}/api/uploads", headers=member_headers, files=files)
        assert r.status_code == 413, r.text


# ---------- /api/uploads audio ----------

class TestAudioUpload:
    def test_upload_audio_mp3(self, member_headers):
        with open(AUDIO_MP3, "rb") as f:
            data = f.read()
        files = {"file": ("audio.mp3", data, "audio/mpeg")}
        r = requests.post(f"{BASE_URL}/api/uploads", headers=member_headers, files=files)
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["media_kind"] == "audio"
        assert body["duration_s"] > 0

    def test_upload_long_audio_rejected(self, member_headers):
        with open(LONG_AUDIO_MP3, "rb") as f:
            data = f.read()
        files = {"file": ("longaudio.mp3", data, "audio/mpeg")}
        r = requests.post(f"{BASE_URL}/api/uploads", headers=member_headers, files=files)
        assert r.status_code == 400, r.text

    def test_upload_oversized_audio(self, member_headers):
        big = b"ID3\x00" + b"\x00" * (21 * 1024 * 1024)
        files = {"file": ("big.mp3", big, "audio/mpeg")}
        r = requests.post(f"{BASE_URL}/api/uploads", headers=member_headers, files=files)
        assert r.status_code == 413, r.text


# ---------- unsupported ----------

class TestUnsupportedUpload:
    def test_reject_text(self, member_headers):
        files = {"file": ("note.txt", b"hello world", "text/plain")}
        r = requests.post(f"{BASE_URL}/api/uploads", headers=member_headers, files=files)
        assert r.status_code == 400


# ---------- /api/uploads/embed ----------

class TestEmbedParser:
    def test_youtube_watch(self, member_headers):
        r = requests.post(f"{BASE_URL}/api/uploads/embed", headers=member_headers,
                          json={"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"})
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["provider"] == "youtube"
        assert body["video_id"] == "dQw4w9WgXcQ"
        assert "embed" in body["embed_url"]
        assert body.get("thumbnail_url")

    def test_youtube_short_url(self, member_headers):
        r = requests.post(f"{BASE_URL}/api/uploads/embed", headers=member_headers,
                          json={"url": "https://youtu.be/dQw4w9WgXcQ"})
        assert r.status_code == 200
        assert r.json()["video_id"] == "dQw4w9WgXcQ"

    def test_youtube_shorts(self, member_headers):
        r = requests.post(f"{BASE_URL}/api/uploads/embed", headers=member_headers,
                          json={"url": "https://www.youtube.com/shorts/dQw4w9WgXcQ"})
        assert r.status_code == 200
        assert r.json()["video_id"] == "dQw4w9WgXcQ"

    def test_vimeo(self, member_headers):
        r = requests.post(f"{BASE_URL}/api/uploads/embed", headers=member_headers,
                          json={"url": "https://vimeo.com/123456789"})
        assert r.status_code == 200
        body = r.json()
        assert body["provider"] == "vimeo"
        assert body["video_id"] == "123456789"
        assert "player.vimeo.com" in body["embed_url"]

    def test_unsupported_url(self, member_headers):
        r = requests.post(f"{BASE_URL}/api/uploads/embed", headers=member_headers,
                          json={"url": "https://example.com/cool-video"})
        assert r.status_code == 400


# ---------- /api/posts media composition ----------

def _upload_image(headers):
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as t:
        tmp = t.name
    subprocess.run(["ffmpeg", "-y", "-f", "lavfi", "-i", "color=c=blue:s=10x10:d=1",
                    "-frames:v", "1", tmp, "-loglevel", "error"], check=True)
    with open(tmp, "rb") as f:
        data = f.read()
    os.unlink(tmp)
    files = {"file": ("a.jpg", data, "image/jpeg")}
    r = requests.post(f"{BASE_URL}/api/uploads", headers=headers, files=files)
    assert r.status_code == 200, r.text
    return r.json()["path"]


def _upload_video(headers):
    with open(SHORT_MP4, "rb") as f:
        data = f.read()
    files = {"file": ("v.mp4", data, "video/mp4")}
    r = requests.post(f"{BASE_URL}/api/uploads", headers=headers, files=files)
    assert r.status_code == 200, r.text
    return r.json()


def _upload_audio(headers):
    with open(AUDIO_MP3, "rb") as f:
        data = f.read()
    files = {"file": ("a.mp3", data, "audio/mpeg")}
    r = requests.post(f"{BASE_URL}/api/uploads", headers=headers, files=files)
    assert r.status_code == 200, r.text
    return r.json()


class TestPostsMedia:
    def test_short_post_with_mixed_media(self, member_headers):
        img1 = _upload_image(member_headers)
        img2 = _upload_image(member_headers)
        vid = _upload_video(member_headers)
        aud = _upload_audio(member_headers)
        payload = {
            "kind": "post",
            "text": "Post with media gallery",
            "media": [
                {"kind": "image", "path": img1},
                {"kind": "image", "path": img2},
                {"kind": "video", "path": vid["path"], "thumbnail_path": vid.get("thumbnail_path"),
                 "duration_s": vid["duration_s"], "width": vid["width"], "height": vid["height"]},
                {"kind": "audio", "path": aud["path"], "duration_s": aud["duration_s"]},
            ],
        }
        r = requests.post(f"{BASE_URL}/api/posts", headers=member_headers, json=payload)
        assert r.status_code == 200, r.text
        pid = r.json()["post_id"]
        # Verify via mine feed
        mine = requests.get(f"{BASE_URL}/api/posts/mine", headers=member_headers)
        assert mine.status_code == 200
        items = mine.json()["items"]
        post = next((p for p in items if p["post_id"] == pid), None)
        assert post is not None
        assert len(post["media"]) == 4
        kinds = [m["kind"] for m in post["media"]]
        assert kinds.count("image") == 2
        assert "video" in kinds and "audio" in kinds

    def test_short_post_5_images_rejected(self, member_headers):
        img = _upload_image(member_headers)
        payload = {
            "kind": "post",
            "text": "Too many images",
            "media": [{"kind": "image", "path": img} for _ in range(5)],
        }
        r = requests.post(f"{BASE_URL}/api/posts", headers=member_headers, json=payload)
        assert r.status_code == 422, r.text

    def test_short_post_two_videos_rejected(self, member_headers):
        v1 = _upload_video(member_headers)
        v2 = _upload_video(member_headers)
        payload = {
            "kind": "post",
            "text": "Two videos",
            "media": [
                {"kind": "video", "path": v1["path"]},
                {"kind": "video", "path": v2["path"]},
            ],
        }
        r = requests.post(f"{BASE_URL}/api/posts", headers=member_headers, json=payload)
        assert r.status_code == 422

    def test_video_plus_embed_rejected(self, member_headers):
        v = _upload_video(member_headers)
        payload = {
            "kind": "post",
            "text": "Video + embed",
            "media": [
                {"kind": "video", "path": v["path"]},
                {"kind": "embed", "provider": "youtube", "embed_url": "https://www.youtube.com/embed/abc12345"},
            ],
        }
        r = requests.post(f"{BASE_URL}/api/posts", headers=member_headers, json=payload)
        assert r.status_code == 422

    def test_essay_with_media(self, member_headers):
        img = _upload_image(member_headers)
        body = "x " * 200
        payload = {
            "kind": "essay",
            "title": "Essay with media",
            "text": body,
            "media": [{"kind": "image", "path": img}],
        }
        r = requests.post(f"{BASE_URL}/api/posts", headers=member_headers, json=payload)
        assert r.status_code == 200, r.text
        pid = r.json()["post_id"]
        # essay detail
        ed = requests.get(f"{BASE_URL}/api/essays/{pid}", headers=member_headers)
        assert ed.status_code == 200
        body_json = ed.json()
        assert len(body_json["media"]) == 1
        assert body_json["media"][0]["kind"] == "image"

    def test_essay_too_short_rejected(self, member_headers):
        payload = {"kind": "essay", "title": "Hi", "text": "too short"}
        r = requests.post(f"{BASE_URL}/api/posts", headers=member_headers, json=payload)
        assert r.status_code == 422

    def test_essay_missing_title_rejected(self, member_headers):
        payload = {"kind": "essay", "text": "x" * 200}
        r = requests.post(f"{BASE_URL}/api/posts", headers=member_headers, json=payload)
        assert r.status_code == 422


# ---------- legacy back-compat ----------

class TestLegacyBackCompat:
    def test_legacy_image_path_surfaces_in_media(self, member_headers):
        img = _upload_image(member_headers)
        # Old-style payload using only image_path
        payload = {"kind": "post", "text": "legacy", "image_path": img}
        r = requests.post(f"{BASE_URL}/api/posts", headers=member_headers, json=payload)
        assert r.status_code == 200, r.text
        pid = r.json()["post_id"]
        mine = requests.get(f"{BASE_URL}/api/posts/mine", headers=member_headers)
        post = next(p for p in mine.json()["items"] if p["post_id"] == pid)
        assert post["media"] and post["media"][0]["kind"] == "image"
        assert post["media"][0]["path"] == img


# ---------- drafts ----------

class TestDraftMedia:
    def test_draft_persists_media(self, member_headers):
        img = _upload_image(member_headers)
        payload = {"kind": "post", "text": "draft text",
                   "media": [{"kind": "image", "path": img}]}
        r = requests.put(f"{BASE_URL}/api/drafts/mine", headers=member_headers, json=payload)
        assert r.status_code == 200, r.text
        g = requests.get(f"{BASE_URL}/api/drafts/mine", headers=member_headers)
        assert g.status_code == 200
        d = g.json()
        assert d.get("media") and d["media"][0]["kind"] == "image"
        # cleanup
        requests.delete(f"{BASE_URL}/api/drafts/mine", headers=member_headers)


# ---------- feeds ----------

class TestFeeds:
    def test_public_feed_returns_media(self, member_headers):
        img = _upload_image(member_headers)
        r = requests.post(f"{BASE_URL}/api/posts", headers=member_headers,
                          json={"kind": "post", "text": "feed media", "media": [{"kind": "image", "path": img}]})
        assert r.status_code == 200
        pub = requests.get(f"{BASE_URL}/api/posts/public")
        assert pub.status_code == 200
        items = pub.json()["items"]
        # Just verify all returned posts include a media list
        for it in items[:10]:
            assert "media" in it
